const QUICK_QUESTIONS = [
  {
    id: '1',
    icon: '📋',
    titleEn: 'File an FIR',
    titleUr: 'ایف آئی آر درج کریں',
    questionEn: 'How do I file an FIR? What are my rights when filing a First Information Report?',
    questionUr: 'میں ایف آئی آر کیسے درج کراؤں؟ ایف آئی آر درج کراتے وقت میرے کیا حقوق ہیں؟',
    category: 'criminal',
  },
  {
    id: '2',
    icon: '⚖️',
    titleEn: 'Bail Rights',
    titleUr: 'ضمانت کے حقوق',
    questionEn: 'What are my rights regarding bail? How can I apply for bail in Pakistan?',
    questionUr: 'ضمانت کے بارے میں میرے کیا حقوق ہیں؟ پاکستان میں ضمانت کے لیے کیسے درخواست دیں؟',
    category: 'criminal',
  },
  {
    id: '3',
    icon: '👩‍👧',
    titleEn: "Women's Rights",
    titleUr: 'خواتین کے حقوق',
    questionEn: 'What are the legal protections for women in Pakistan under the Protection of Women Act?',
    questionUr: 'پاکستان میں خواتین کے تحفظ کا قانون کیا کہتا ہے؟ خواتین کو کیا قانونی تحفظ حاصل ہے؟',
    category: 'women',
  },
  {
    id: '4',
    icon: '💍',
    titleEn: 'Divorce / Khula',
    titleUr: 'طلاق / خلع',
    questionEn: 'What is the procedure for khula (divorce initiated by wife) in Pakistan?',
    questionUr: 'پاکستان میں خلع کا طریقہ کار کیا ہے؟ بیوی طلاق کیسے لے سکتی ہے؟',
    category: 'family',
  },
  {
    id: '5',
    icon: '🪪',
    titleEn: 'CNIC / NADRA',
    titleUr: 'شناختی کارڈ / نادرا',
    questionEn: 'How do I get a new CNIC or renew my national identity card through NADRA?',
    questionUr: 'نادرا سے نیا شناختی کارڈ کیسے بنوائیں یا پرانا کارڈ کیسے تجدید کریں؟',
    category: 'nadra',
  },
  {
    id: '6',
    icon: '🏠',
    titleEn: 'Tenant Rights',
    titleUr: 'کرایہ دار کے حقوق',
    questionEn: 'What are my rights as a tenant in Pakistan? Can my landlord evict me without notice?',
    questionUr: 'پاکستان میں بطور کرایہ دار میرے کیا حقوق ہیں؟ کیا مالک مکان بغیر نوٹس کے نکال سکتا ہے؟',
    category: 'property',
  },
  {
    id: '7',
    icon: '👷',
    titleEn: 'Labor Rights',
    titleUr: 'مزدور کے حقوق',
    questionEn: 'What are my labor rights in Pakistan? What can I do if my employer is not paying my salary?',
    questionUr: 'پاکستان میں مزدور کے کیا حقوق ہیں؟ اگر آجر تنخواہ نہ دے تو کیا کریں؟',
    category: 'labor',
  },
  {
    id: '8',
    icon: '🚔',
    titleEn: 'Police Arrest Rights',
    titleUr: 'گرفتاری کے حقوق',
    questionEn: 'What are my rights if I am arrested by police in Pakistan? What should I do?',
    questionUr: 'اگر پولیس مجھے گرفتار کرے تو میرے کیا حقوق ہیں؟ مجھے کیا کرنا چاہیے؟',
    category: 'criminal',
  },
];

export default QUICK_QUESTIONS;
